use voco;

-- MySQL Script generated by MySQL Workbench
-- Mon Apr 28 03:26:22 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema voco
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `voco` ;

-- -----------------------------------------------------
-- Schema voco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `voco` DEFAULT CHARACTER SET utf8mb3 ;

-- -----------------------------------------------------
-- Table `voco`.`words`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voco`.`words` (
  `word_id` INT NOT NULL AUTO_INCREMENT,
  `word` VARCHAR(100) NOT NULL,
  `phonetic` VARCHAR(100) NULL DEFAULT NULL,
  `definition` TEXT NOT NULL,
  `part_of_speech` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`word_id`),
  INDEX `idx_word` (`word` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `mydb`.`translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voco`.`translation` (
  `translation_id` INT NOT NULL,
  `word_id` INT NOT NULL,
  `abbreviation` VARCHAR(45) NOT NULL,
  `translation` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`translation_id`),
  INDEX `fk_translation_words1_idx` (`word_id` ASC) VISIBLE,
  CONSTRAINT `fk_translation_words1`
    FOREIGN KEY (`word_id`)
    REFERENCES `voco`.`words` (`word_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`example_sentence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voco`.`example_sentence` (
  `example_id` INT NOT NULL,
  `sentence` TEXT NULL,
  `translation` TEXT NULL,
  `translation_translation_id` INT NOT NULL,
  PRIMARY KEY (`example_id`),
  INDEX `fk_example_sentence_translation_idx` (`translation_translation_id` ASC) VISIBLE,
  CONSTRAINT `fk_example_sentence_translation`
    FOREIGN KEY (`translation_translation_id`)
    REFERENCES `mydb`.`translation` (`translation_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `voco` ;

-- -----------------------------------------------------
-- Table `voco`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voco`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `daily_goal` INT NULL DEFAULT '20',
  `streak_days` INT NULL DEFAULT '0',
  `total_words_learned` INT NULL DEFAULT '0',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `username` (`username` ASC) VISIBLE,
  INDEX `idx_username` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `voco`.`study_records`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voco`.`study_records` (
  `record_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `date` DATE NOT NULL,
  `words_learned` INT NULL DEFAULT '0',
  `words_reviewed` INT NULL DEFAULT '0',
  `study_duration` INT NULL DEFAULT '0',
  PRIMARY KEY (`record_id`),
  UNIQUE INDEX `uk_user_date` (`user_id` ASC, `date` ASC) VISIBLE,
  INDEX `idx_date` (`date` ASC) VISIBLE,
  INDEX `idx_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `study_records_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `voco`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `voco`.`user_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voco`.`user_settings` (
  `setting_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `daily_reminder` TINYINT(1) NULL DEFAULT '1',
  `reminder_time` TIME NULL DEFAULT '20:00:00',
  PRIMARY KEY (`setting_id`),
  UNIQUE INDEX `uk_user` (`user_id` ASC) VISIBLE,
  CONSTRAINT `user_settings_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `voco`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `voco`.`user_words`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voco`.`user_words` (
  `user_word_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `word_id` INT NOT NULL,
  `memory_status` ENUM('remembered', 'vague', 'unlearned') NULL DEFAULT 'unlearned',
  `review_count` INT NULL DEFAULT '0',
  `last_reviewed` TIMESTAMP NULL DEFAULT NULL,
  `next_review` TIMESTAMP NULL DEFAULT NULL,
  `familiarity_score` INT NULL DEFAULT '0',
  PRIMARY KEY (`user_word_id`),
  UNIQUE INDEX `uk_user_word` (`user_id` ASC, `word_id` ASC) VISIBLE,
  INDEX `word_id` (`word_id` ASC) VISIBLE,
  INDEX `idx_memory_status` (`memory_status` ASC) VISIBLE,
  INDEX `idx_next_review` (`next_review` ASC) VISIBLE,
  INDEX `idx_user_memory` (`user_id` ASC, `memory_status` ASC) VISIBLE,
  CONSTRAINT `user_words_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `voco`.`users` (`user_id`)
    ON DELETE CASCADE,
  CONSTRAINT `user_words_ibfk_2`
    FOREIGN KEY (`word_id`)
    REFERENCES `voco`.`words` (`word_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `voco`.`wordbooks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voco`.`wordbooks` (
  `wordbook_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `is_public` TINYINT(1) NULL DEFAULT '0',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`wordbook_id`),
  INDEX `idx_user` (`user_id` ASC) VISIBLE,
  INDEX `idx_public` (`is_public` ASC) VISIBLE,
  CONSTRAINT `wordbooks_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `voco`.`users` (`user_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `voco`.`wordbook_contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voco`.`wordbook_contents` (
  `content_id` INT NOT NULL AUTO_INCREMENT,
  `wordbook_id` INT NOT NULL,
  `word_id` INT NOT NULL,
  `added_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`content_id`),
  UNIQUE INDEX `uk_wordbook_word` (`wordbook_id` ASC, `word_id` ASC) VISIBLE,
  INDEX `idx_wordbook` (`wordbook_id` ASC) VISIBLE,
  INDEX `idx_word` (`word_id` ASC) VISIBLE,
  CONSTRAINT `wordbook_contents_ibfk_1`
    FOREIGN KEY (`wordbook_id`)
    REFERENCES `voco`.`wordbooks` (`wordbook_id`)
    ON DELETE CASCADE,
  CONSTRAINT `wordbook_contents_ibfk_2`
    FOREIGN KEY (`word_id`)
    REFERENCES `voco`.`words` (`word_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
